---
packages:
  default:
    # Utils linux
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - guake
    - xclip
    - keepassxc
    - htop
    - net-tools
    - meld
    - snapd

  development:
    - curl
    - shellcheck
    - git
    - apache2
    # TODO need snap or add ppa ?
#    - pgadmin4

  server:
    - ufw
    - fail2ban
    - nginx

  snap:
    - discord
    - skypeforlinux
    - slack-desktop

  dpkg:
    - sublime-text
    - sublime-merge

java_version: "11"
programs_install_docker: "True"